# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04128cea8cca7ee365b12d9e6e79e662387e814a5aff1e236ff85ba82d34e2a3a062460a7dd1def05f01211309b9a27418e07fd12dce3b7d0bce40689cb3dce2

test:
  secret_key_base: 7250cf7b2be183be2fe91a8a76e8c2307d6d9fae264ce8596ae3c341ca5204ab3b992bffd1fbfe64450c12a8e3a82ed1740e5cea49008f6839c77f7350d67aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
